version: 2
jobs:
  restore:
    docker:
      - image: mcr.microsoft.com/dotnet/core-nightly/sdk:3.0.100-rc1-alpine3.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - wcbot-{{ checksum "TelegramBot.Core/TelegramBot.Core.csproj" }}
            - wcbot-
      - run: |
          ##change the directory from the solution folder to project
          cd TelegramBot.Core
          ##appsettings & appsettings.Migration replaces
          sed -i.bak "s/_DEFAULT_CONNECTION_/${DEFAULT_CONNECTION}/g" appsettings.json
          sed -i.bak "s/_MIGRATION_DEFAULT_CONNECTION_/${MIGRATION_DEFAULT_CONNECTION}/g" appsettings.Migration.json
          sed -i.bak "s/_TOKEN_/${TOKEN}/g" appsettings.json
          sed -i.bak "s#_WEBHOOK_URL_#${WEBHOOK_URL}#g" appsettings.json ##specific delimiter
          dotnet restore
      - save_cache:
          key: wcbot-{{ checksum "TelegramBot.Core/TelegramBot.Core.csproj" }}
          paths:
            - ./bin
            - ./obj
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core-nightly/sdk:3.0.100-rc1-alpine3.10
    steps:
      - attach_workspace:
          at: .
      - run: |
          cd TelegramBot.Tests
          dotnet restore
          dotnet test
  build_image:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -t $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest -t $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH -t $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH-$CIRCLE_SHA1 .
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME
  migrate:
    docker:
      - image: mcr.microsoft.com/dotnet/core-nightly/sdk:3.0.100-rc1-alpine3.10
    steps:
      - attach_workspace:
          at: .
      - run: |
          cd TelegramBot.Core
          PATH=$PATH:/root/.dotnet/tools ASPNETCORE_ENVIRONMENT=Migration dotnet tool install -g dotnet-ef --version 3.0.0-preview8.19405.11
          PATH=$PATH:/root/.dotnet/tools ASPNETCORE_ENVIRONMENT=Migration dotnet ef database update
  stop_image:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - attach_workspace:
          at: .
      - run: |
          ##stop currently working image
          ssh -o "StrictHostKeyChecking=no" $REMOTE_USERNAME@$REMOTE_HOST "cd ${REMOTE_PATH} && docker-compose -f docker-compose.prod.yml down"
          ##docker-compose replaces
          sed -i.bak "s/_HTTP_PORT_/${HTTP_PORT}/g" docker-compose.prod.yml
          sed -i.bak "s#_DOCKER_IMAGE_#$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH-$CIRCLE_SHA1#g" docker-compose.prod.yml
          ##send the docker-compose file to the remote hosting (as soon as it's hosted at a single server, not cluster)
          scp -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null"  docker-compose.prod.yml $REMOTE_USERNAME@$REMOTE_HOST:$REMOTE_PATH
  start_image:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - attach_workspace:
          at: .
      - run: ssh -o "StrictHostKeyChecking=no" $REMOTE_USERNAME@$REMOTE_HOST "cd ${REMOTE_PATH} && docker-compose -f docker-compose.prod.yml build && docker-compose -f docker-compose.prod.yml up -d"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - restore:
          filters:
            branches:
              only: master
      - test:
          requires:
            - restore
      - build_image:
          requires:
            - test
          filters:
            branches:
              only: master
      - stop_image:
          requires:
            - test
            - build_image
      - migrate:
          requires:
            - test
            - stop_image
      - start_image:
          requires:
            - build_image
            - migrate
